server:
  port: 2001
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
mybatis:
  mapper-locations:
    - "classpath*:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
logging:
  pattern:
    console:  '%clr(%d{HH:mm:ss}){yellow} [%clr(%thread){red}] %-5level %clr(%logger){green} | %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  level:
    com.demo.*: debug
  file:
    max-history: 30
    path: d:/logs/demo
